# Angola|Benin|Botswana|Burkina Faso|Burundi|Cabo Verde|Cameroon|Central African Republic|Chad|Comoros|Congo|Cote d'Ivoire|Equatorial Guinea|Eritrea|Swaziland|Ethiopia|Gabon|Gambia, The|Ghana|Guinea|Guinea-Bissau|Kenya|Lesotho|Liberia|Madagascar|Malawi|Mali|Mauritania|Mauritius|Mozambique|Namibia|Niger|Nigeria|Rwanda|Sao Tome and Principe|Senegal|Seychelles|Sierra Leone|Somalia|South Africa|South Sudan|Sudan|Tanzania|Togo|Uganda|Zambia|Zimbabwe
# Brunei|Cambodia|Timor-Leste|Indonesia|Laos|Malaysia|Philippines|Singapore|Thailand|Vietnam
# Armenia|Azerbaijan|Bahrain|Cyprus|Georgia|Iraq|Israel|Jordan|Kuwait|Lebanon|Oman|Qatar|Saudi Arabia|Syria|Turkey|United Arab Emirates|Yemen
# Mexico|Guatemala|Honduras|Nicaragua|El Salvador|Costa Rica|Panama|Belize
# Australia|Papua New Guinea|New Zealand|Fiji|Solomon Islands|Micronesia|Vanuatu|Samoa|Kiribati|Tonga|Marshall Islands|Palau|Tuvalu|Nauru

COUNTRIES = [
    {
        "code": "AD",
        "lat": 42.546245,
        "lon": 1.601554,
        "country": "Andorra",
        "zone": None,
    },
    {
        "code": "AE",
        "lat": 23.424076,
        "lon": 53.847818,
        "country": "United Arab Emirates",
        "zone": "south_west_asia",
    },
    {
        "code": "AF",
        "lat": 33.93911,
        "lon": 67.709953,
        "country": "Afghanistan",
        "zone": None,
    },
    {
        "code": "AG",
        "lat": 17.060816,
        "lon": -61.796428,
        "country": "Antigua and Barbuda",
        "zone": None,
    },
    {
        "code": "AI",
        "lat": 18.220554,
        "lon": -63.068615,
        "country": "Anguilla",
        "zone": None,
    },
    {
        "code": "AL",
        "lat": 41.153332,
        "lon": 20.168331,
        "country": "Albania",
        "zone": None,
    },
    {
        "code": "AM",
        "lat": 40.069099,
        "lon": 45.038189,
        "country": "Armenia",
        "zone": "south_west_asia",
    },
    {
        "code": "AN",
        "lat": 12.226079,
        "lon": -69.060087,
        "country": "Netherlands Antilles",
        "zone": None,
    },
    {
        "code": "AO",
        "lat": -11.202692,
        "lon": 17.873887,
        "country": "Angola",
        "zone": "south_africa",
    },
    {
        "code": "AQ",
        "lat": -75.250973,
        "lon": -0.071389,
        "country": "Antarctica",
        "zone": None,
    },
    {
        "code": "AR",
        "lat": -38.416097,
        "lon": -63.616672,
        "country": "Argentina",
        "zone": None,
    },
    {
        "code": "AS",
        "lat": -14.270972,
        "lon": -170.132217,
        "country": "American Samoa",
        "zone": "oceania",
    },
    {
        "code": "AT",
        "lat": 47.516231,
        "lon": 14.550072,
        "country": "Austria",
        "zone": None,
    },
    {
        "code": "AU",
        "lat": -25.274398,
        "lon": 133.775136,
        "country": "Australia",
        "zone": "oceania",
    },
    {
        "code": "AW",
        "lat": 12.52111,
        "lon": -69.968338,
        "country": "Aruba",
        "zone": None,
    },
    {
        "code": "AZ",
        "lat": 40.143105,
        "lon": 47.576927,
        "country": "Azerbaijan",
        "zone": "south_west_asia",
    },
    {
        "code": "BA",
        "lat": 43.915886,
        "lon": 17.679076,
        "country": "Bosnia and Herzegovina",
        "zone": None,
    },
    {
        "code": "BB",
        "lat": 13.193887,
        "lon": -59.543198,
        "country": "Barbados",
        "zone": None,
    },
    {
        "code": "BD",
        "lat": 23.684994,
        "lon": 90.356331,
        "country": "Bangladesh",
        "zone": None,
    },
    {
        "code": "BE",
        "lat": 50.503887,
        "lon": 4.469936,
        "country": "Belgium",
        "zone": None,
    },
    {
        "code": "BF",
        "lat": 12.238333,
        "lon": -1.561593,
        "country": "Burkina Faso",
        "zone": "south_africa",
    },
    {
        "code": "BG",
        "lat": 42.733883,
        "lon": 25.48583,
        "country": "Bulgaria",
        "zone": None,
    },
    {
        "code": "BH",
        "lat": 25.930414,
        "lon": 50.637772,
        "country": "Bahrain",
        "zone": "south_west_asia",
    },
    {
        "code": "BI",
        "lat": -3.373056,
        "lon": 29.918886,
        "country": "Burundi",
        "zone": "south_africa",
    },
    {
        "code": "BJ",
        "lat": 9.30769,
        "lon": 2.315834,
        "country": "Benin",
        "zone": "south_africa",
    },
    {
        "code": "BM",
        "lat": 32.321384,
        "lon": -64.75737,
        "country": "Bermuda",
        "zone": None,
    },
    {
        "code": "BN",
        "lat": 4.535277,
        "lon": 114.727669,
        "country": "Brunei",
        "zone": "south_east_asia",
    },
    {
        "code": "BO",
        "lat": -16.290154,
        "lon": -63.588653,
        "country": "Bolivia",
        "zone": None,
    },
    {
        "code": "BR",
        "lat": -14.235004,
        "lon": -51.92528,
        "country": "Brazil",
        "zone": None,
    },
    {
        "code": "BS",
        "lat": 25.03428,
        "lon": -77.39628,
        "country": "Bahamas",
        "zone": None,
    },
    {
        "code": "BT",
        "lat": 27.514162,
        "lon": 90.433601,
        "country": "Bhutan",
        "zone": None,
    },
    {
        "code": "BV",
        "lat": -54.423199,
        "lon": 3.413194,
        "country": "Bouvet Island",
        "zone": None,
    },
    {
        "code": "BW",
        "lat": -22.328474,
        "lon": 24.684866,
        "country": "Botswana",
        "zone": "south_africa",
    },
    {
        "code": "BY",
        "lat": 53.709807,
        "lon": 27.953389,
        "country": "Belarus",
        "zone": None,
    },
    {
        "code": "BZ",
        "lat": 17.189877,
        "lon": -88.49765,
        "country": "Belize",
        "zone": "central_america",
    },
    {
        "code": "CA",
        "lat": 56.130366,
        "lon": -106.346771,
        "country": "Canada",
        "zone": None,
    },
    {
        "code": "CC",
        "lat": -12.164165,
        "lon": 96.870956,
        "country": "Cocos [Keeling] Islands",
        "zone": None,
    },
    {
        "code": "CD",
        "lat": -4.038333,
        "lon": 21.758664,
        "country": "Congo [DRC]",
        "zone": "south_africa",
    },
    {
        "code": "CF",
        "lat": 6.611111,
        "lon": 20.939444,
        "country": "Central African Republic",
        "zone": "south_africa",
    },
    {
        "code": "CG",
        "lat": -0.228021,
        "lon": 15.827659,
        "country": "Congo [Republic]",
        "zone": "south_africa",
    },
    {
        "code": "CH",
        "lat": 46.818188,
        "lon": 8.227512,
        "country": "Switzerland",
        "zone": None,
    },
    {
        "code": "CI",
        "lat": 7.539989,
        "lon": -5.54708,
        "country": "Côte d'Ivoire",
        "zone": None,
    },
    {
        "code": "CK",
        "lat": -21.236736,
        "lon": -159.777671,
        "country": "Cook Islands",
        "zone": None,
    },
    {
        "code": "CL",
        "lat": -35.675147,
        "lon": -71.542969,
        "country": "Chile",
        "zone": None,
    },
    {
        "code": "CM",
        "lat": 7.369722,
        "lon": 12.354722,
        "country": "Cameroon",
        "zone": "south_africa",
    },
    {
        "code": "CN",
        "lat": 35.86166,
        "lon": 104.195397,
        "country": "China",
        "zone": None,
    },
    {
        "code": "CO",
        "lat": 4.570868,
        "lon": -74.297333,
        "country": "Colombia",
        "zone": None,
    },
    {
        "code": "CR",
        "lat": 9.748917,
        "lon": -83.753428,
        "country": "Costa Rica",
        "zone": "central_america",
    },
    {
        "code": "CU",
        "lat": 21.521757,
        "lon": -77.781167,
        "country": "Cuba",
        "zone": None,
    },
    {
        "code": "CV",
        "lat": 16.002082,
        "lon": -24.013197,
        "country": "Cape Verde",
        "zone": None,
    },
    {
        "code": "CX",
        "lat": -10.447525,
        "lon": 105.690449,
        "country": "Christmas Island",
        "zone": None,
    },
    {
        "code": "CY",
        "lat": 35.126413,
        "lon": 33.429859,
        "country": "Cyprus",
        "zone": "south_west_asia",
    },
    {
        "code": "CZ",
        "lat": 49.817492,
        "lon": 15.472962,
        "country": "Czech Republic",
        "zone": None,
    },
    {
        "code": "DE",
        "lat": 51.165691,
        "lon": 10.451526,
        "country": "Germany",
        "zone": None,
    },
    {
        "code": "DJ",
        "lat": 11.825138,
        "lon": 42.590275,
        "country": "Djibouti",
        "zone": None,
    },
    {
        "code": "DK",
        "lat": 56.26392,
        "lon": 9.501785,
        "country": "Denmark",
        "zone": None,
    },
    {
        "code": "DM",
        "lat": 15.414999,
        "lon": -61.370976,
        "country": "Dominica",
        "zone": None,
    },
    {
        "code": "DO",
        "lat": 18.735693,
        "lon": -70.162651,
        "country": "Dominican Republic",
        "zone": None,
    },
    {
        "code": "DZ",
        "lat": 28.033886,
        "lon": 1.659626,
        "country": "Algérie",
        "zone": "north_africa",
    },
    {
        "code": "EC",
        "lat": -1.831239,
        "lon": -78.183406,
        "country": "Ecuador",
        "zone": None,
    },
    {
        "code": "EE",
        "lat": 58.595272,
        "lon": 25.013607,
        "country": "Estonia",
        "zone": None,
    },
    {
        "code": "EG",
        "lat": 26.820553,
        "lon": 30.802498,
        "country": "Égypte",
        "zone": "north_africa",
    },
    {
        "code": "EH",
        "lat": 24.215527,
        "lon": -12.885834,
        "country": "Sahara Occidental",
        "zone": "north_africa",
    },
    {
        "code": "ER",
        "lat": 15.179384,
        "lon": 39.782334,
        "country": "Eritrea",
        "zone": "south_africa",
    },
    {
        "code": "ES",
        "lat": 40.463667,
        "lon": -3.74922,
        "country": "Spain",
        "zone": None,
    },
    {
        "code": "ET",
        "lat": 9.145,
        "lon": 40.489673,
        "country": "Ethiopia",
        "zone": "south_africa",
    },
    {
        "code": "FI",
        "lat": 61.92411,
        "lon": 25.748151,
        "country": "Finland",
        "zone": None,
    },
    {
        "code": "FJ",
        "lat": -16.578193,
        "lon": 179.414413,
        "country": "Fiji",
        "zone": "oceania",
    },
    {
        "code": "FK",
        "lat": -51.796253,
        "lon": -59.523613,
        "country": "Falkland Islands [Islas Malvinas]",
        "zone": None,
    },
    {
        "code": "FM",
        "lat": 7.425554,
        "lon": 150.550812,
        "country": "Micronesia",
        "zone": "oceania",
    },
    {
        "code": "FO",
        "lat": 61.892635,
        "lon": -6.911806,
        "country": "Faroe Islands",
        "zone": None,
    },
    {
        "code": "FR",
        "lat": 46.227638,
        "lon": 2.213749,
        "country": "France",
        "zone": None,
    },
    {
        "code": "GA",
        "lat": -0.803689,
        "lon": 11.609444,
        "country": "Gabon",
        "zone": "south_africa",
    },
    {
        "code": "GB",
        "lat": 55.378051,
        "lon": -3.435973,
        "country": "United Kingdom",
        "zone": None,
    },
    {
        "code": "GD",
        "lat": 12.262776,
        "lon": -61.604171,
        "country": "Grenada",
        "zone": None,
    },
    {
        "code": "GE",
        "lat": 42.315407,
        "lon": 43.356892,
        "country": "Georgia",
        "zone": "south_west_asia",
    },
    {
        "code": "GF",
        "lat": 3.933889,
        "lon": -53.125782,
        "country": "French Guiana",
        "zone": None,
    },
    {
        "code": "GG",
        "lat": 49.465691,
        "lon": -2.585278,
        "country": "Guernsey",
        "zone": None,
    },
    {
        "code": "GH",
        "lat": 7.946527,
        "lon": -1.023194,
        "country": "Ghana",
        "zone": "south_africa",
    },
    {
        "code": "GI",
        "lat": 36.137741,
        "lon": -5.345374,
        "country": "Gibraltar",
        "zone": None,
    },
    {
        "code": "GL",
        "lat": 71.706936,
        "lon": -42.604303,
        "country": "Greenland",
        "zone": None,
    },
    {
        "code": "GM",
        "lat": 13.443182,
        "lon": -15.310139,
        "country": "Gambia",
        "zone": None,
    },
    {
        "code": "GN",
        "lat": 9.945587,
        "lon": -9.696645,
        "country": "Guinea",
        "zone": "south_africa",
    },
    {
        "code": "GP",
        "lat": 16.995971,
        "lon": -62.067641,
        "country": "Guadeloupe",
        "zone": None,
    },
    {
        "code": "GQ",
        "lat": 1.650801,
        "lon": 10.267895,
        "country": "Equatorial Guinea",
        "zone": "south_africa",
    },
    {
        "code": "GR",
        "lat": 39.074208,
        "lon": 21.824312,
        "country": "Greece",
        "zone": None,
    },
    {
        "code": "GS",
        "lat": -54.429579,
        "lon": -36.587909,
        "country": "South Georgia and the South Sandwich Islands",
        "zone": "south_west_asia",
    },
    {
        "code": "GT",
        "lat": 15.783471,
        "lon": -90.230759,
        "country": "Guatemala",
        "zone": "central_america",
    },
    {
        "code": "GU",
        "lat": 13.444304,
        "lon": 144.793731,
        "country": "Guam",
        "zone": None,
    },
    {
        "code": "GW",
        "lat": 11.803749,
        "lon": -15.180413,
        "country": "Guinea-Bissau",
        "zone": "south_africa",
    },
    {
        "code": "GY",
        "lat": 4.860416,
        "lon": -58.93018,
        "country": "Guyana",
        "zone": None,
    },
    {
        "code": "GZ",
        "lat": 31.354676,
        "lon": 34.308825,
        "country": "Gaza Strip",
        "zone": None,
    },
    {
        "code": "HK",
        "lat": 22.396428,
        "lon": 114.109497,
        "country": "Hong Kong",
        "zone": None,
    },
    {
        "code": "HM",
        "lat": -53.08181,
        "lon": 73.504158,
        "country": "Heard Island and McDonald Islands",
        "zone": None,
    },
    {
        "code": "HN",
        "lat": 15.199999,
        "lon": -86.241905,
        "country": "Honduras",
        "zone": "central_america",
    },
    {
        "code": "HR",
        "lat": 45.1,
        "lon": 15.2,
        "country": "Croatia",
        "zone": None,
    },
    {
        "code": "HT",
        "lat": 18.971187,
        "lon": -72.285215,
        "country": "Haiti",
        "zone": None,
    },
    {
        "code": "HU",
        "lat": 47.162494,
        "lon": 19.503304,
        "country": "Hungary",
        "zone": None,
    },
    {
        "code": "ID",
        "lat": -0.789275,
        "lon": 113.921327,
        "country": "Indonesia",
        "zone": "south_east_asia",
    },
    {
        "code": "IE",
        "lat": 53.41291,
        "lon": -8.24389,
        "country": "Ireland",
        "zone": None,
    },
    {
        "code": "IL",
        "lat": 31.046051,
        "lon": 34.851612,
        "country": "Israel",
        "zone": "south_west_asia",
    },
    {
        "code": "IM",
        "lat": 54.236107,
        "lon": -4.548056,
        "country": "Isle of Man",
        "zone": None,
    },
    {
        "code": "IN",
        "lat": 20.593684,
        "lon": 78.96288,
        "country": "India",
        "zone": None,
    },
    {
        "code": "IO",
        "lat": -6.343194,
        "lon": 71.876519,
        "country": "British Indian Ocean Territory",
        "zone": None,
    },
    {
        "code": "IQ",
        "lat": 33.223191,
        "lon": 43.679291,
        "country": "Iraq",
        "zone": "south_west_asia",
    },
    {
        "code": "IR",
        "lat": 32.427908,
        "lon": 53.688046,
        "country": "Iran",
        "zone": None,
    },
    {
        "code": "IS",
        "lat": 64.963051,
        "lon": -19.020835,
        "country": "Iceland",
        "zone": None,
    },
    {
        "code": "IT",
        "lat": 41.87194,
        "lon": 12.56738,
        "country": "Italy",
        "zone": None,
    },
    {
        "code": "JE",
        "lat": 49.214439,
        "lon": -2.13125,
        "country": "Jersey",
        "zone": None,
    },
    {
        "code": "JM",
        "lat": 18.109581,
        "lon": -77.297508,
        "country": "Jamaica",
        "zone": None,
    },
    {
        "code": "JO",
        "lat": 30.585164,
        "lon": 36.238414,
        "country": "Jordan",
        "zone": "south_west_asia",
    },
    {
        "code": "JP",
        "lat": 36.204824,
        "lon": 138.252924,
        "country": "Japan",
        "zone": None,
    },
    {
        "code": "KE",
        "lat": -0.023559,
        "lon": 37.906193,
        "country": "Kenya",
        "zone": "south_africa",
    },
    {
        "code": "KG",
        "lat": 41.20438,
        "lon": 74.766098,
        "country": "Kyrgyzstan",
        "zone": None,
    },
    {
        "code": "KH",
        "lat": 12.565679,
        "lon": 104.990963,
        "country": "Cambodia",
        "zone": "south_east_asia",
    },
    {
        "code": "KI",
        "lat": -3.370417,
        "lon": -168.734039,
        "country": "Kiribati",
        "zone": "oceania",
    },
    {
        "code": "KM",
        "lat": -11.875001,
        "lon": 43.872219,
        "country": "Comoros",
        "zone": "south_africa",
    },
    {
        "code": "KN",
        "lat": 17.357822,
        "lon": -62.782998,
        "country": "Saint Kitts and Nevis",
        "zone": None,
    },
    {
        "code": "KP",
        "lat": 40.339852,
        "lon": 127.510093,
        "country": "North Korea",
        "zone": None,
    },
    {
        "code": "KR",
        "lat": 35.907757,
        "lon": 127.766922,
        "country": "South Korea",
        "zone": None,
    },
    {
        "code": "KW",
        "lat": 29.31166,
        "lon": 47.481766,
        "country": "Kuwait",
        "zone": "south_west_asia",
    },
    {
        "code": "KY",
        "lat": 19.513469,
        "lon": -80.566956,
        "country": "Cayman Islands",
        "zone": None,
    },
    {
        "code": "KZ",
        "lat": 48.019573,
        "lon": 66.923684,
        "country": "Kazakhstan",
        "zone": None,
    },
    {
        "code": "LA",
        "lat": 19.85627,
        "lon": 102.495496,
        "country": "Laos",
        "zone": "south_east_asia",
    },
    {
        "code": "LB",
        "lat": 33.854721,
        "lon": 35.862285,
        "country": "Lebanon",
        "zone": "south_west_asia",
    },
    {
        "code": "LC",
        "lat": 13.909444,
        "lon": -60.978893,
        "country": "Saint Lucia",
        "zone": None,
    },
    {
        "code": "LI",
        "lat": 47.166,
        "lon": 9.555373,
        "country": "Liechtenstein",
        "zone": None,
    },
    {
        "code": "LK",
        "lat": 7.873054,
        "lon": 80.771797,
        "country": "Sri Lanka",
        "zone": None,
    },
    {
        "code": "LR",
        "lat": 6.428055,
        "lon": -9.429499,
        "country": "Liberia",
        "zone": "south_africa",
    },
    {
        "code": "LS",
        "lat": -29.609988,
        "lon": 28.233608,
        "country": "Lesotho",
        "zone": "south_africa",
    },
    {
        "code": "LT",
        "lat": 55.169438,
        "lon": 23.881275,
        "country": "Lithuania",
        "zone": None,
    },
    {
        "code": "LU",
        "lat": 49.815273,
        "lon": 6.129583,
        "country": "Luxembourg",
        "zone": None,
    },
    {
        "code": "LV",
        "lat": 56.879635,
        "lon": 24.603189,
        "country": "Latvia",
        "zone": None,
    },
    {
        "code": "LY",
        "lat": 26.3351,
        "lon": 17.228331,
        "country": "Libye",
        "zone": "north_africa",
    },
    {
        "code": "MA",
        "lat": 31.791702,
        "lon": -7.09262,
        "country": "Maroc",
        "zone": "north_africa",
    },
    {
        "code": "MC",
        "lat": 43.750298,
        "lon": 7.412841,
        "country": "Monaco",
        "zone": None,
    },
    {
        "code": "MD",
        "lat": 47.411631,
        "lon": 28.369885,
        "country": "Moldova",
        "zone": None,
    },
    {
        "code": "ME",
        "lat": 42.708678,
        "lon": 19.37439,
        "country": "Montenegro",
        "zone": None,
    },
    {
        "code": "MG",
        "lat": -18.766947,
        "lon": 46.869107,
        "country": "Madagascar",
        "zone": "south_africa",
    },
    {
        "code": "MH",
        "lat": 7.131474,
        "lon": 171.184478,
        "country": "Marshall Islands",
        "zone": "oceania",
    },
    {
        "code": "MK",
        "lat": 41.608635,
        "lon": 21.745275,
        "country": "Macedonia [FYROM]",
        "zone": None,
    },
    {
        "code": "ML",
        "lat": 17.570692,
        "lon": -3.996166,
        "country": "Mali",
        "zone": "south_africa",
    },
    {
        "code": "MM",
        "lat": 21.913965,
        "lon": 95.956223,
        "country": "Myanmar [Burma]",
        "zone": "south_east_asia",
    },
    {
        "code": "MN",
        "lat": 46.862496,
        "lon": 103.846656,
        "country": "Mongolia",
        "zone": None,
    },
    {
        "code": "MO",
        "lat": 22.198745,
        "lon": 113.543873,
        "country": "Macau",
        "zone": None,
    },
    {
        "code": "MP",
        "lat": 17.33083,
        "lon": 145.38469,
        "country": "Northern Mariana Islands",
        "zone": None,
    },
    {
        "code": "MQ",
        "lat": 14.641528,
        "lon": -61.024174,
        "country": "Martinique",
        "zone": None,
    },
    {
        "code": "MR",
        "lat": 21.00789,
        "lon": -10.940835,
        "country": "Mauritania",
        "zone": "south_africa",
    },
    {
        "code": "MS",
        "lat": 16.742498,
        "lon": -62.187366,
        "country": "Montserrat",
        "zone": None,
    },
    {
        "code": "MT",
        "lat": 35.937496,
        "lon": 14.375416,
        "country": "Malta",
        "zone": None,
    },
    {
        "code": "MU",
        "lat": -20.348404,
        "lon": 57.552152,
        "country": "Mauritius",
        "zone": "south_africa",
    },
    {
        "code": "MV",
        "lat": 3.202778,
        "lon": 73.22068,
        "country": "Maldives",
        "zone": None,
    },
    {
        "code": "MW",
        "lat": -13.254308,
        "lon": 34.301525,
        "country": "Malawi",
        "zone": "south_africa",
    },
    {
        "code": "MX",
        "lat": 23.634501,
        "lon": -102.552784,
        "country": "Mexico",
        "zone": "central_america",
    },
    {
        "code": "MY",
        "lat": 4.210484,
        "lon": 101.975766,
        "country": "Malaysia",
        "zone": "south_east_asia",
    },
    {
        "code": "MZ",
        "lat": -18.665695,
        "lon": 35.529562,
        "country": "Mozambique",
        "zone": "south_africa",
    },
    {
        "code": "NA",
        "lat": -22.95764,
        "lon": 18.49041,
        "country": "Namibia",
        "zone": "south_africa",
    },
    {
        "code": "NC",
        "lat": -20.904305,
        "lon": 165.618042,
        "country": "New Caledonia",
        "zone": None,
    },
    {
        "code": "NE",
        "lat": 17.607789,
        "lon": 8.081666,
        "country": "Niger",
        "zone": "south_africa",
    },
    {
        "code": "NF",
        "lat": -29.040835,
        "lon": 167.954712,
        "country": "Norfolk Island",
        "zone": None,
    },
    {
        "code": "NG",
        "lat": 9.081999,
        "lon": 8.675277,
        "country": "Nigeria",
        "zone": "south_africa",
    },
    {
        "code": "NI",
        "lat": 12.865416,
        "lon": -85.207229,
        "country": "Nicaragua",
        "zone": "central_america",
    },
    {
        "code": "NL",
        "lat": 52.132633,
        "lon": 5.291266,
        "country": "Netherlands",
        "zone": None,
    },
    {
        "code": "NO",
        "lat": 60.472024,
        "lon": 8.468946,
        "country": "Norway",
        "zone": None,
    },
    {
        "code": "NP",
        "lat": 28.394857,
        "lon": 84.124008,
        "country": "Nepal",
        "zone": None,
    },
    {
        "code": "NR",
        "lat": -0.522778,
        "lon": 166.931503,
        "country": "Nauru",
        "zone": "oceania",
    },
    {
        "code": "NU",
        "lat": -19.054445,
        "lon": -169.867233,
        "country": "Niue",
        "zone": None,
    },
    {
        "code": "NZ",
        "lat": -40.900557,
        "lon": 174.885971,
        "country": "New Zealand",
        "zone": "oceania",
    },
    {
        "code": "OM",
        "lat": 21.512583,
        "lon": 55.923255,
        "country": "Oman",
        "zone": "south_west_asia",
    },
    {
        "code": "PA",
        "lat": 8.537981,
        "lon": -80.782127,
        "country": "Panama",
        "zone": "central_america",
    },
    {
        "code": "PE",
        "lat": -9.189967,
        "lon": -75.015152,
        "country": "Peru",
        "zone": None,
    },
    {
        "code": "PF",
        "lat": -17.679742,
        "lon": -149.406843,
        "country": "French Polynesia",
        "zone": None,
    },
    {
        "code": "PG",
        "lat": -6.314993,
        "lon": 143.95555,
        "country": "Papua New Guinea",
        "zone": "oceania",
    },
    {
        "code": "PH",
        "lat": 12.879721,
        "lon": 121.774017,
        "country": "Philippines",
        "zone": "south_east_asia",
    },
    {
        "code": "PK",
        "lat": 30.375321,
        "lon": 69.345116,
        "country": "Pakistan",
        "zone": None,
    },
    {
        "code": "PL",
        "lat": 51.919438,
        "lon": 19.145136,
        "country": "Poland",
        "zone": None,
    },
    {
        "code": "PM",
        "lat": 46.941936,
        "lon": -56.27111,
        "country": "Saint Pierre and Miquelon",
        "zone": None,
    },
    {
        "code": "PN",
        "lat": -24.703615,
        "lon": -127.439308,
        "country": "Pitcairn Islands",
        "zone": None,
    },
    {
        "code": "PR",
        "lat": 18.220833,
        "lon": -66.590149,
        "country": "Puerto Rico",
        "zone": None,
    },
    {
        "code": "PS",
        "lat": 31.952162,
        "lon": 35.233154,
        "country": "Palestinian Territories",
        "zone": None,
    },
    {
        "code": "PT",
        "lat": 39.399872,
        "lon": -8.224454,
        "country": "Portugal",
        "zone": None,
    },
    {
        "code": "PW",
        "lat": 7.51498,
        "lon": 134.58252,
        "country": "Palau",
        "zone": "oceania",
    },
    {
        "code": "PY",
        "lat": -23.442503,
        "lon": -58.443832,
        "country": "Paraguay",
        "zone": None,
    },
    {
        "code": "QA",
        "lat": 25.354826,
        "lon": 51.183884,
        "country": "Qatar",
        "zone": "south_west_asia",
    },
    {
        "code": "RE",
        "lat": -21.115141,
        "lon": 55.536384,
        "country": "Réunion",
        "zone": None,
    },
    {
        "code": "RO",
        "lat": 45.943161,
        "lon": 24.96676,
        "country": "Romania",
        "zone": "south_west_asia",
    },
    {
        "code": "RS",
        "lat": 44.016521,
        "lon": 21.005859,
        "country": "Serbia",
        "zone": None,
    },
    {
        "code": "RU",
        "lat": 61.52401,
        "lon": 105.318756,
        "country": "Russia",
        "zone": None,
    },
    {
        "code": "RW",
        "lat": -1.940278,
        "lon": 29.873888,
        "country": "Rwanda",
        "zone": "south_africa",
    },
    {
        "code": "SA",
        "lat": 23.885942,
        "lon": 45.079162,
        "country": "Saudi Arabia",
        "zone": "south_west_asia",
    },
    {
        "code": "SB",
        "lat": -9.64571,
        "lon": 160.156194,
        "country": "Solomon Islands",
        "zone": "oceania",
    },
    {
        "code": "SC",
        "lat": -4.679574,
        "lon": 55.491977,
        "country": "Seychelles",
        "zone": "south_africa",
    },
    {
        "code": "SD",
        "lat": 12.862807,
        "lon": 30.217636,
        "country": "Sudan",
        "zone": "south_africa",
    },
    {
        "code": "SE",
        "lat": 60.128161,
        "lon": 18.643501,
        "country": "Sweden",
        "zone": None,
    },
    {
        "code": "SG",
        "lat": 1.352083,
        "lon": 103.819836,
        "country": "Singapore",
        "zone": "south_east_asia",
    },
    {
        "code": "SH",
        "lat": -24.143474,
        "lon": -10.030696,
        "country": "Saint Helena",
        "zone": None,
    },
    {
        "code": "SI",
        "lat": 46.151241,
        "lon": 14.995463,
        "country": "Slovenia",
        "zone": None,
    },
    {
        "code": "SJ",
        "lat": 77.553604,
        "lon": 23.670272,
        "country": "Svalbard and Jan Mayen",
        "zone": None,
    },
    {
        "code": "SK",
        "lat": 48.669026,
        "lon": 19.699024,
        "country": "Slovakia",
        "zone": None,
    },
    {
        "code": "SL",
        "lat": 8.460555,
        "lon": -11.779889,
        "country": "Sierra Leone",
        "zone": "south_africa",
    },
    {
        "code": "SM",
        "lat": 43.94236,
        "lon": 12.457777,
        "country": "San Marino",
        "zone": None,
    },
    {
        "code": "SN",
        "lat": 14.497401,
        "lon": -14.452362,
        "country": "Senegal",
        "zone": "south_africa",
    },
    {
        "code": "SO",
        "lat": 5.152149,
        "lon": 46.199616,
        "country": "Somalia",
        "zone": "south_africa",
    },
    {
        "code": "SR",
        "lat": 3.919305,
        "lon": -56.027783,
        "country": "Suriname",
        "zone": None,
    },
    {
        "code": "ST",
        "lat": 0.18636,
        "lon": 6.613081,
        "country": "São Tomé and Príncipe",
        "zone": None,
    },
    {
        "code": "SV",
        "lat": 13.794185,
        "lon": -88.89653,
        "country": "El Salvador",
        "zone": "central_america",
    },
    {
        "code": "SY",
        "lat": 34.802075,
        "lon": 38.996815,
        "country": "Syria",
        "zone": "south_west_asia",
    },
    {
        "code": "SZ",
        "lat": -26.522503,
        "lon": 31.465866,
        "country": "Swaziland",
        "zone": "south_africa",
    },
    {
        "code": "TC",
        "lat": 21.694025,
        "lon": -71.797928,
        "country": "Turks and Caicos Islands",
        "zone": None,
    },
    {
        "code": "TD",
        "lat": 15.454166,
        "lon": 18.732207,
        "country": "Chad",
        "zone": "south_africa",
    },
    {
        "code": "TF",
        "lat": -49.280366,
        "lon": 69.348557,
        "country": "French Southern Territories",
        "zone": None,
    },
    {
        "code": "TG",
        "lat": 8.619543,
        "lon": 0.824782,
        "country": "Togo",
        "zone": "south_africa",
    },
    {
        "code": "TH",
        "lat": 15.870032,
        "lon": 100.992541,
        "country": "Thailand",
        "zone": "south_east_asia",
    },
    {
        "code": "TJ",
        "lat": 38.861034,
        "lon": 71.276093,
        "country": "Tajikistan",
        "zone": None,
    },
    {
        "code": "TK",
        "lat": -8.967363,
        "lon": -171.855881,
        "country": "Tokelau",
        "zone": None,
    },
    {
        "code": "TL",
        "lat": -8.874217,
        "lon": 125.727539,
        "country": "Timor-Leste",
        "zone": "south_east_asia",
    },
    {
        "code": "TM",
        "lat": 38.969719,
        "lon": 59.556278,
        "country": "Turkmenistan",
        "zone": None,
    },
    {
        "code": "TN",
        "lat": 33.886917,
        "lon": 9.537499,
        "country": "Tunisie",
        "zone": "north_africa",
    },
    {
        "code": "TO",
        "lat": -21.178986,
        "lon": -175.198242,
        "country": "Tonga",
        "zone": "oceania",
    },
    {
        "code": "TR",
        "lat": 38.963745,
        "lon": 35.243322,
        "country": "Turkey",
        "zone": "south_west_asia",
    },
    {
        "code": "TT",
        "lat": 10.691803,
        "lon": -61.222503,
        "country": "Trinidad and Tobago",
        "zone": None,
    },
    {
        "code": "TV",
        "lat": -7.109535,
        "lon": 177.64933,
        "country": "Tuvalu",
        "zone": "oceania",
    },
    {
        "code": "TW",
        "lat": 23.69781,
        "lon": 120.960515,
        "country": "Taiwan",
        "zone": None,
    },
    {
        "code": "TZ",
        "lat": -6.369028,
        "lon": 34.888822,
        "country": "Tanzania",
        "zone": "south_africa",
    },
    {
        "code": "UA",
        "lat": 48.379433,
        "lon": 31.16558,
        "country": "Ukraine",
        "zone": None,
    },
    {
        "code": "UG",
        "lat": 1.373333,
        "lon": 32.290275,
        "country": "Uganda",
        "zone": "south_africa",
    },
    {
        "code": "US",
        "lat": 37.09024,
        "lon": -95.712891,
        "country": "United States",
        "zone": None,
    },
    {
        "code": "UY",
        "lat": -32.522779,
        "lon": -55.765835,
        "country": "Uruguay",
        "zone": None,
    },
    {
        "code": "UZ",
        "lat": 41.377491,
        "lon": 64.585262,
        "country": "Uzbekistan",
        "zone": None,
    },
    {
        "code": "VA",
        "lat": 41.902916,
        "lon": 12.453389,
        "country": "Vatican City",
        "zone": None,
    },
    {
        "code": "VC",
        "lat": 12.984305,
        "lon": -61.287228,
        "country": "Saint Vincent and the Grenadines",
        "zone": None,
    },
    {
        "code": "VE",
        "lat": 6.42375,
        "lon": -66.58973,
        "country": "Venezuela",
        "zone": None,
    },
    {
        "code": "VG",
        "lat": 18.420695,
        "lon": -64.639968,
        "country": "British Virgin Islands",
        "zone": None,
    },
    {
        "code": "VI",
        "lat": 18.335765,
        "lon": -64.896335,
        "country": "U.S. Virgin Islands",
        "zone": None,
    },
    {
        "code": "VN",
        "lat": 14.058324,
        "lon": 108.277199,
        "country": "Vietnam",
        "zone": "south_east_asia",
    },
    {
        "code": "VU",
        "lat": -15.376706,
        "lon": 166.959158,
        "country": "Vanuatu",
        "zone": "oceania",
    },
    {
        "code": "WF",
        "lat": -13.768752,
        "lon": -177.156097,
        "country": "Wallis and Futuna",
        "zone": None,
    },
    {
        "code": "WS",
        "lat": -13.759029,
        "lon": -172.104629,
        "country": "Samoa",
        "zone": "oceania",
    },
    {
        "code": "XK",
        "lat": 42.602636,
        "lon": 20.902977,
        "country": "Kosovo",
        "zone": None,
    },
    {
        "code": "YE",
        "lat": 15.552727,
        "lon": 48.516388,
        "country": "Yemen",
        "zone": "south_west_asia",
    },
    {
        "code": "YT",
        "lat": -12.8275,
        "lon": 45.166244,
        "country": "Mayotte",
        "zone": None,
    },
    {
        "code": "ZA",
        "lat": -30.559482,
        "lon": 22.937506,
        "country": "South Africa",
        "zone": "south_africa",
    },
    {
        "code": "ZM",
        "lat": -13.133897,
        "lon": 27.849332,
        "country": "Zambia",
        "zone": "south_africa",
    },
    {
        "code": "ZW",
        "lat": -19.015438,
        "lon": 29.154857,
        "country": "Zimbabwe",
        "zone": "south_africa",
    },
]

COUNTRY_CHOICES = (
    ("Afrique du Sud", "Afrique du Sud"),
    ("Algérie", "Algérie"),
    ("Angola", "Angola"),
    ("Bénin", "Bénin"),
    ("Botswana", "Botswana"),
    ("Burkina Faso", "Burkina Faso"),
    ("Burundi", "Burundi"),
    ("Cameroun", "Cameroun"),
    ("Cap-Vert", "Cap-Vert"),
    ("République centrafricaine", "République centrafricaine"),
    ("Comores", "Comores"),
    ("République du Congo", "République du Congo"),
    (
        "République démocratique du Congo",
        "République démocratique du Congo",
    ),
    ("Côte d'Ivoire", "Côte d'Ivoire"),
    ("Djibouti", "Djibouti"),
    ("Égypte", "Égypte"),
    ("Érythrée", "Érythrée"),
    ("Swaziland", "Eswatini"),
    ("Éthiopie", "Éthiopie"),
    ("Gabon", "Gabon"),
    ("Gambie", "Gambie"),
    ("Ghana", "Ghana"),
    ("Guinée", "Guinée"),
    ("Guinée-Bissau", "Guinée-Bissau"),
    ("Guinée équatoriale", "Guinée équatoriale"),
    ("Kenya", "Kenya"),
    ("Lesotho", "Lesotho"),
    ("Liberia", "Liberia"),
    ("Libye", "Libye"),
    ("Madagascar", "Madagascar"),
    ("Malawi", "Malawi"),
    ("Mali", "Mali"),
    ("Maroc", "Maroc"),
    ("Maurice", "Maurice"),
    ("Mauritanie", "Mauritanie"),
    ("Mozambique", "Mozambique"),
    ("Namibie", "Namibie"),
    ("Niger", "Niger"),
    ("Nigeria", "Nigeria"),
    ("Ouganda", "Ouganda"),
    ("Rwanda", "Rwanda"),
    ("São Tomé-et-Principe", "São Tomé-et-Principe"),
    ("Sénégal", "Sénégal"),
    ("Seychelles", "Seychelles"),
    ("Sierra Leone", "Sierra Leone"),
    ("Somalie", "Somalie"),
    ("Soudan", "Soudan"),
    ("Soudan du Sud", "Soudan du Sud"),
    ("Tanzanie", "Tanzanie"),
    ("Tchad", "Tchad"),
    ("Togo", "Togo"),
    ("Tunisie", "Tunisie"),
    ("Zambie", "Zambie"),
    ("Zimbabwe", "Zimbabwe"),
    ("Tanzanie", "Tanzanie"),
    ("Tchad", "Tchad"),
    ("Togo", "Togo"),
    ("Tunisie", "Tunisie"),
    ("Zambie", "Zambie"),
    ("Zimbabwe", "Zimbabwe"),
    ("Tanzanie", "Tanzanie"),
    ("Tchad", "Tchad"),
    ("Togo", "Togo"),
    ("Tunisie", "Tunisie"),
    ("Zambie", "Zambie"),
    ("Zimbabwe", "Zimbabwe"),
)
