# Generated by Django 3.2.19 on 2023-05-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progysat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geozone',
            options={'verbose_name': 'zone géographique', 'verbose_name_plural': 'zones géographiques'},
        ),
        migrations.AddField(
            model_name='geozone',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Nom en'),
        ),
        migrations.AddField(
            model_name='geozone',
            name='name_fr',
            field=models.CharField(default='', max_length=100, verbose_name='Nom fr'),
        ),
        migrations.AddField(
            model_name='geozone',
            name='name_nl',
            field=models.CharField(default='', max_length=100, verbose_name='Nom nl'),
        ),
        migrations.AddField(
            model_name='geozone',
            name='name_pt_br',
            field=models.CharField(default='', max_length=100, verbose_name='Nom pt-br'),
        ),
        migrations.AddField(
            model_name='geozone',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='geozone',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='translation_key',
        ),
    ]
