# Generated by Django 3.2.19 on 2023-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('progysat', '0002_auto_20230515_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldZone',
            new_name='GeoZone',
        ),
        migrations.AlterModelOptions(
            name='geozone',
            options={'ordering': ('name',), 'verbose_name': 'zone géographique', 'verbose_name_plural': 'zones géographiques'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='countries',
        ),
        migrations.AlterField(
            model_name='news',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text="Ce champ n'est pas encore utilisé", to='progysat.GeoZone', verbose_name='Zones géographique liées'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
