# Generated by Django 3.2.19 on 2023-05-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progysat', '0002_auto_20230518_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name='Slug (URL de la ressource)'),
        ),
    ]
