# Generated by Django 3.2.19 on 2023-05-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('progysat', '0003_alter_resource_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(default='', max_length=100, verbose_name='Nom fr')),
                ('name_en', models.CharField(default='', max_length=100, verbose_name='Nom en')),
                ('name_pt_br', models.CharField(default='', max_length=100, verbose_name='Nom pt-br')),
                ('name_nl', models.CharField(default='', max_length=100, verbose_name='Nom nl')),
                ('order', models.FloatField(help_text='Les images du bas seront présentées par ordre croissant', verbose_name='ordre')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Image en bas de footer',
                'verbose_name_plural': 'Images en bas de footer',
                'ordering': ('order',),
            },
        ),
    ]
