# Generated by Django 3.2.19 on 2023-05-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progysat', '0004_footerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerdetail',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='lien'),
        ),
    ]
