# Generated by Django 3.2.19 on 2023-05-31 16:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('progysat', '0007_alter_thematic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thematic',
            name='description',
        ),
        migrations.AddField(
            model_name='thematic',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, default='', max_length=1000, null=True, verbose_name='Description en'),
        ),
        migrations.AddField(
            model_name='thematic',
            name='description_fr',
            field=wagtail.fields.RichTextField(blank=True, default='', max_length=1000, null=True, verbose_name='Description fr'),
        ),
        migrations.AddField(
            model_name='thematic',
            name='description_nl',
            field=wagtail.fields.RichTextField(blank=True, default='', max_length=1000, null=True, verbose_name='Description nl'),
        ),
        migrations.AddField(
            model_name='thematic',
            name='description_pt_br',
            field=wagtail.fields.RichTextField(blank=True, default='', max_length=1000, null=True, verbose_name='Description pt-br'),
        ),
        migrations.AlterField(
            model_name='thematic',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document', verbose_name='Image principale'),
        ),
    ]
