# Generated by Django 3.2.19 on 2023-05-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progysat', '0009_thematicslistpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='types',
        ),
        migrations.DeleteModel(
            name='ActualityType',
        ),
    ]
