# Generated by Django 3.2.19 on 2023-06-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progysat', '0011_auto_20230602_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geozone',
            name='icon',
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='news',
            name='zones',
        ),
        migrations.DeleteModel(
            name='GeoZone',
        ),
    ]
