# Generated by Django 3.2.19 on 2023-06-08 15:19

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('progysat', '0012_auto_20230602_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link', 'h2'], label='Contenu', required=True)), ('color', wagtail.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('color', wagtail.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False)), ('columns', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('color', wagtail.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text='Corps de la page', use_json_field=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', label='Titre de la page')), ('section', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link', 'h2'], label='Contenu', required=True)), ('color', wagtail.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image à côté du paragraphe', required=False)), ('position', wagtail.blocks.ChoiceBlock(choices=[('right', 'Droite'), ('left', 'Gauche')], help_text="Position de l'image", required=False)), ('sub_section', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('color', wagtail.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False)), ('columns', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('color', wagtail.blocks.ChoiceBlock(choices=[('blue-light', 'Bleue'), ('secondary-light', 'Rose'), ('white', 'Blanche'), ('', 'Sans couleur')], help_text='Couleur de fond', label='couleur', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'h3', 'h4', 'ol', 'ul', 'document-link'], label='Contenu', required=False))], label='Colonne'), label='Colonnes'))], label='Sous section'), default=[], label='Sous sections'))], label='Section')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('pdf', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, help_text='Corps de la page', use_json_field=True, verbose_name='Contenu'),
        ),
    ]
