# Generated by Django 3.2.19 on 2023-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progysat', '0013_auto_20230608_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="ce champ est rempli automatiquement s'il est laissé vide", max_length=100, verbose_name="Slug (URL de l'actualité)"),
        ),
    ]
